//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOI.AppicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOI_Offs
    {
        public int id_off { get; set; }
        public int off_asset_own_id { get; set; }
        public System.DateTime off_date { get; set; }
        public string off_reason { get; set; }
        public string off_document_link { get; set; }
        public int off_responsible_user_id { get; set; }
    
        public virtual SOI_Owns SOI_Owns { get; set; }
        public virtual SOI_Users SOI_Users { get; set; }
    }
}
