//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOI.AppicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOI_Reports
    {
        public int id_report { get; set; }
        public int report_type_id { get; set; }
        public System.DateTime report_creation_date { get; set; }
        public string report_theme { get; set; }
        public string report_comment { get; set; }
        public string report_link { get; set; }
        public int report_creator_user_id { get; set; }
    
        public virtual SOI_Report_Types SOI_Report_Types { get; set; }
        public virtual SOI_Users SOI_Users { get; set; }
    }
}
