//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOI.AppicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOI_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOI_Users()
        {
            this.SOI_Answers = new HashSet<SOI_Answers>();
            this.SOI_Offs = new HashSet<SOI_Offs>();
            this.SOI_Owns = new HashSet<SOI_Owns>();
            this.SOI_Reports = new HashSet<SOI_Reports>();
            this.SOI_Requests = new HashSet<SOI_Requests>();
        }
    
        public int id_user { get; set; }
        public string user_first_name { get; set; }
        public string user_last_name { get; set; }
        public string user_surname { get; set; }
        public string user_position { get; set; }
        public string user_phone { get; set; }
        public string user_mail { get; set; }
        public int user_role_id { get; set; }
        public string user_login { get; set; }
        public string user_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOI_Answers> SOI_Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOI_Offs> SOI_Offs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOI_Owns> SOI_Owns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOI_Reports> SOI_Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOI_Requests> SOI_Requests { get; set; }
        public virtual SOI_User_Roles SOI_User_Roles { get; set; }
    }
}
