//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOI.AppicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOI_Answers
    {
        public int id_request_answer { get; set; }
        public int answer_user_id { get; set; }
        public System.DateTime answer_date { get; set; }
        public int answer_request_id { get; set; }
        public int answer_asset_id { get; set; }
    
        public virtual SOI_Assets SOI_Assets { get; set; }
        public virtual SOI_Requests SOI_Requests { get; set; }
        public virtual SOI_Users SOI_Users { get; set; }
    }
}
