//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOI.AppicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOI_Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOI_Requests()
        {
            this.SOI_Answers = new HashSet<SOI_Answers>();
        }
    
        public int id_request { get; set; }
        public int reguest_user_id { get; set; }
        public System.DateTime request_date { get; set; }
        public int request_status_id { get; set; }
        public string request_comment { get; set; }
        public int request_asset_type_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOI_Answers> SOI_Answers { get; set; }
        public virtual SOI_Asset_Types SOI_Asset_Types { get; set; }
        public virtual SOI_Reques_Statuses SOI_Reques_Statuses { get; set; }
        public virtual SOI_Users SOI_Users { get; set; }
    }
}
