//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOI.AppicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOI_Assets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOI_Assets()
        {
            this.SOI_Answers = new HashSet<SOI_Answers>();
            this.SOI_Owns = new HashSet<SOI_Owns>();
        }
    
        public int id_asset { get; set; }
        public string asset_name { get; set; }
        public int asset_type_id { get; set; }
        public string asset_serial_number { get; set; }
        public int asset_status_id { get; set; }
        public string asset_comment { get; set; }
        public int asset_location_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOI_Answers> SOI_Answers { get; set; }
        public virtual SOI_Asset_Statuses SOI_Asset_Statuses { get; set; }
        public virtual SOI_Asset_Types SOI_Asset_Types { get; set; }
        public virtual SOI_Locations SOI_Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOI_Owns> SOI_Owns { get; set; }
    }
}
