//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOI.AppicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOI_Owns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOI_Owns()
        {
            this.SOI_Offs = new HashSet<SOI_Offs>();
        }
    
        public int id_asset_own { get; set; }
        public int own_asset_id { get; set; }
        public int own_user_id { get; set; }
        public System.DateTime own_date { get; set; }
    
        public virtual SOI_Assets SOI_Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOI_Offs> SOI_Offs { get; set; }
        public virtual SOI_Users SOI_Users { get; set; }
    }
}
